version: '3.8'

services:
  mail-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-forwarder
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      # For HTTP-01 challenge (optional)
      - "80:80"
      # For TLS-ALPN-01 challenge (optional)
      - "443:443"
    volumes:
      - dkim-keys:/etc/opendkim/keys
      - letsencrypt:/etc/letsencrypt
      - postfix-spool:/var/spool/postfix
    environment:
      # Basic configuration
      - SMTP_HOSTNAME=mail.example.com
      - ACME_EMAIL=admin@example.com
      
      # Forwarding rules
      - FORWARD_RULES=user1@example.com:external1@gmail.com;user2@example.com:external2@outlook.com;*@example.com:catchall@gmail.com
      
      # DKIM configuration (enabled by default)
      # - DKIM_ENABLED=false          # Optional: Set to false to disable
      - DKIM_SELECTOR=mail
      
      # TLS configuration (enabled by default)
      # - TLS_ENABLED=false           # Optional: Set to false to disable
      - TLS_CHALLENGE_TYPE=tls-alpn
      - TLS_STAGING=false
      
      # Security configuration (enabled by default)
      # - FAIL2BAN_ENABLED=false      # Optional: Set to false to disable
      - FAIL2BAN_MAX_ATTEMPTS=5
      
      # SRS configuration (enabled by default)
      # - SRS_ENABLED=false           # Optional: Set to false to disable
      # - SRS_SECRET=your-secret-key           # Optional: Default is randomly generated
      # - SRS_DOMAIN=srs.example.com           # Optional: Default is SMTP_HOSTNAME
      # - SRS_EXCLUDE_DOMAINS=example.org,example.net  # Optional: Default is none
      
      # SMTP relay configuration (optional)
      # - SMTP_RELAY_HOST=smtp.gmail.com
      # - SMTP_RELAY_PORT=587
      # - SMTP_RELAY_USERNAME=your-username@gmail.com
      # - SMTP_RELAY_PASSWORD=your-password
      # - SMTP_RELAY_USE_TLS=true
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "/scripts/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  dkim-keys:
    driver: local
  letsencrypt:
    driver: local
  postfix-spool:
    driver: local 