#!/bin/sh

(sleep 10; find /downloads -type l | while read in; do
    file "$in" | grep "broken symbolic link"
    if [ $? -ne 1 ]; then
        echo "Delete $in"
        rm -f "$in"
    fi
done

find /downloads -type d -empty -exec rm -r {} \;) >> /tmp/postrm.log &
